# Generated by Django 5.1.1 on 2024-09-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_yourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
