# Generated by Django 5.1.1 on 2024-09-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_inn_delete_yourmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='inn',
        ),
    ]
