version: '3.8'

services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: FastAPI_ITM
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/docker/app.sh"]
    depends_on:
      - postgres_db
      - rabbitmq
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:admin@postgres_db:5432/FastAPI_ITM"
      CELERY_BROKER_URL: "pyamqp://guest@rabbitmq//"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_worker.celery_app worker --loglevel=info
    depends_on:
      - rabbitmq
      - postgres_db
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:admin@postgres_db:5432/FastAPI_ITM"
      CELERY_BROKER_URL: "pyamqp://guest@rabbitmq//"
