"""Change add commit

Revision ID: 0799a87ed57d
Revises: cc941e76c24c
Create Date: 2024-09-01 21:16:27.207564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0799a87ed57d'
down_revision: Union[str, None] = 'cc941e76c24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Поставщик', 'Коментарий')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Поставщик', sa.Column('Коментарий', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
